# Generated by Django 3.2.13 on 2022-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('trichy', 'trichy'), ('madurai', 'madurai')], default='trichy', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('chennai', 'chennai'), ('trichy', 'trichy')], default='chennai', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('sleeper', 'sleeper'), ('general', 'general')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookdate',
            field=models.DateTimeField(),
        ),
    ]
